### ISSUE TITLE
mdadm: no more than 256 raid-devices supported for level 6

### ISSUE THREAD

**Issue by munikiel** [md-raid-utilities/mdadm#6]
Trying to create a raid6 like this

```
# mdadm --create --level=6 --raid-devices=257 /dev/md1
mdadm: no more than 256 raid-devices supported for level 6
```

claims you can go up to 256 drives.

However it's actually 255!

With 256, you get a BUG_ON kernel panic crypto/async_tx/async_pq.c:309

```
#define MAX_DISKS 255
       BUG_ON(disks < 4 || disks > MAX_DISKS);
```

Problem is once you hit this BUG_ON even once, the md subsystem seems to not recover from it. You can no longer stop the array or do anything else.

**Comment by mtkaczyk** [comment]
Hello @munikiel,
Thanks for the report. I checked MD driver briefly and it looks like that we don't control how many drives are added in new_dev_store(). I think that the simplest and best is to fix verification in mdadm but let me consult it with MD developers.

**Comment by mtkaczyk** [comment]
Hey @munikiel,
This limitation may not be needed these days and for sure we have to fix driver from going to BUG_ON condition.
Could you please fill kernel bug against MD driver?
https://bugzilla.kernel.org/

As soon as report will be submitted, the community will help to remove this BUG_ON or if that is not possible, block MD from binding to much drives to raid6 array.

mdadm code is the lowest priority problem, right now. We will keep it open until the discussion on ML is settled down and we will adjust mdadm code appropriately later.

**Comment by ktanska** [comment]
@munikiel are you going to report this issue?

**Comment by mtkaczyk** [comment]
No support from submitter. I do realize that it is a bug but it seems that there is no interest in support us to have it fixed. For that reason I'm closing it.

**Comment by munikiel** [comment]
I stumbled over this issue while using mdadm, and out of naive thought that users should report any bugs they encounter, did just that with as much detail I could possibly provided. I simply do not have anything else to add.

bugzilla has red flashing warning sign telling me loudly to go elsewhere - _If you did not compile your own kernel from scratch, you are probably in the wrong place_. - Yes I did not and I will not be using that site at all then. I don't even see this as a kernel bug anyway, so reporting it as one is not my bailiwick. And I don't understand this bug reporting culture where it somehow depends on me to copy-paste it around. How does this actually help?

I have since found other seemingly minor bugs in mdadm, which I won't be reporting at all then since all it seems to achieve is wasting time on both ends. Which was not my intention at all so I'm sorry about that.

Good bye then,

**Comment by mtkaczyk** [comment]
> I stumbled over this issue while using mdadm, and out of naive thought that users should report any bugs they encounter, did just that with as much detail I could possibly provided. I simply do not have anything else to add.

This is open source, we would love to help but we also expect to have your support on that. We will help, if we see that someone cares (especially in corner cases like this one). If no one want to have it solved, we will choose to do more important topic.

This case is more complex because we realized that there are multiple ways to have it solved, we can fix mdadm for sure but MD maintainers feels like this limitation is no longer required (and that option is preferred by them).  So I asked to create kernel bug. 

> bugzilla has red flashing warning sign telling me loudly to go elsewhere - If you did not compile your own kernel from scratch, you are probably in the wrong place. - Yes I did not and I will not be using that site at all then. I don't even see this as a kernel bug anyway, so reporting it as one is not my bailiwick. And I don't understand this bug reporting culture where it somehow depends on me to copy-paste it around. How does this actually help?

The same rule applies there- they will help you if they see that it matters for you. That requires you to be ready for kernel compilation. Also, kernel folks didn't get used to work with Github. They prefer mailing lists. In open source world your role is not ended on creating a bug. You may be asked for retests, more logs etc. or filling kernel bug. You are the owner of this story.
Sorry if I disappointed you!

I don't know you that's why I assumed that you as developer similar to me. I thought that you were ready to support with retests. It appears that you are not interested in that. That's fine. Github is still developers space.

> I have since found other seemingly minor bugs in mdadm, which I won't be reporting at all then since all it seems to achieve is wasting time on both ends. Which was not my intention at all so I'm sorry about that.

Please consider helping us in resolving them instead! This is open-source and everybody it free to contribute. I will love to review your patches!
Please see that if everyone will take same approach as you (report all bugs you've ever found) I will not have time for anything else.
